CREATE TABLE IF NOT EXISTS order_tax_snapshots (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    order_type VARCHAR(32) NOT NULL,
    supplier_gstin VARCHAR(20) NULL,
    seller_state_code VARCHAR(8) NULL,
    pos_state_code VARCHAR(8) NULL,
    supply_type VARCHAR(32) NULL,
    total_taxable_value DOUBLE NULL,
    total_gst_amount DOUBLE NULL,
    total_amount_charged DOUBLE NULL,
    total_amount_with_tax DOUBLE NULL,
    total_commission_amount DOUBLE NULL,
    total_commission_gst_amount DOUBLE NULL,
    tcs_rate_percentage DOUBLE NULL,
    tcs_amount DOUBLE NULL,
    gst_rule_version VARCHAR(100) NULL,
    tcs_rule_version VARCHAR(100) NULL,
    snapshot_source VARCHAR(64) NULL,
    snapshot_payload LONGTEXT NULL,
    frozen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_tax_snapshots_order_id (order_id),
    KEY idx_order_tax_snapshots_order_id (order_id)
);
