CREATE TABLE IF NOT EXISTS order_settlements (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT NOT NULL,
    payment_order_id BIGINT NULL,
    seller_id BIGINT NULL,
    order_type VARCHAR(32) NOT NULL,
    settlement_status VARCHAR(32) NOT NULL,
    gross_collected_amount DOUBLE NULL,
    taxable_value DOUBLE NULL,
    gst_amount DOUBLE NULL,
    commission_amount DOUBLE NULL,
    commission_gst_amount DOUBLE NULL,
    tcs_rate_percentage DOUBLE NULL,
    tcs_amount DOUBLE NULL,
    seller_payable_amount DOUBLE NULL,
    seller_gst_liability_amount DOUBLE NULL,
    admin_revenue_amount DOUBLE NULL,
    admin_gst_liability_amount DOUBLE NULL,
    currency_code VARCHAR(8) NULL,
    payout_reference VARCHAR(128) NULL,
    notes TEXT NULL,
    ledger_posted_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_settlements_order_id (order_id),
    KEY idx_order_settlements_payment_order_id (payment_order_id),
    KEY idx_order_settlements_seller_id (seller_id),
    CONSTRAINT fk_order_settlements_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_order_settlements_payment_order FOREIGN KEY (payment_order_id) REFERENCES payment_order (id),
    CONSTRAINT fk_order_settlements_seller FOREIGN KEY (seller_id) REFERENCES seller (id)
);

CREATE TABLE IF NOT EXISTS settlement_ledger_entries (
    id BIGINT NOT NULL AUTO_INCREMENT,
    settlement_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    payment_order_id BIGINT NULL,
    seller_id BIGINT NULL,
    order_type VARCHAR(32) NOT NULL,
    entry_group VARCHAR(64) NOT NULL,
    entry_direction VARCHAR(16) NOT NULL,
    account_code VARCHAR(64) NOT NULL,
    account_name VARCHAR(128) NOT NULL,
    amount DOUBLE NOT NULL,
    currency_code VARCHAR(8) NULL,
    note TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_settlement_ledger_entries_settlement_id (settlement_id),
    KEY idx_settlement_ledger_entries_order_id (order_id),
    KEY idx_settlement_ledger_entries_payment_order_id (payment_order_id),
    KEY idx_settlement_ledger_entries_seller_id (seller_id),
    CONSTRAINT fk_settlement_ledger_entries_settlement FOREIGN KEY (settlement_id) REFERENCES order_settlements (id),
    CONSTRAINT fk_settlement_ledger_entries_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_settlement_ledger_entries_payment_order FOREIGN KEY (payment_order_id) REFERENCES payment_order (id),
    CONSTRAINT fk_settlement_ledger_entries_seller FOREIGN KEY (seller_id) REFERENCES seller (id)
);
