ALTER TABLE orders MODIFY COLUMN order_status VARCHAR(64) NULL;
ALTER TABLE orders MODIFY COLUMN payment_status VARCHAR(64) NULL;
ALTER TABLE orders MODIFY COLUMN status VARCHAR(64) NULL;

UPDATE orders
SET order_status = CASE CAST(order_status AS CHAR)
    WHEN '0' THEN 'PENDING'
    WHEN '1' THEN 'PLACED'
    WHEN '2' THEN 'CONFIRMED'
    WHEN '3' THEN 'SHIPPED'
    WHEN '4' THEN 'OUT_FOR_DELIVERY'
    WHEN '5' THEN 'DELIVERED'
    WHEN '6' THEN 'CANCELLED'
    WHEN 'COMPLETE' THEN 'DELIVERED'
    WHEN 'COMPLETED' THEN 'DELIVERED'
    ELSE order_status
END;

UPDATE orders
SET payment_status = CASE CAST(payment_status AS CHAR)
    WHEN '0' THEN 'PENDING'
    WHEN '1' THEN 'PROCESSING'
    WHEN '2' THEN 'COMPLETED'
    WHEN '3' THEN 'FAILED'
    WHEN 'CAPTURED' THEN 'COMPLETED'
    WHEN 'PAID' THEN 'COMPLETED'
    WHEN 'SUCCESS' THEN 'COMPLETED'
    WHEN 'CREATED' THEN 'PENDING'
    ELSE payment_status
END;

UPDATE orders
SET status = CASE CAST(status AS CHAR)
    WHEN '0' THEN 'PENDING'
    WHEN '1' THEN 'PROCESSING'
    WHEN '2' THEN 'COMPLETED'
    WHEN '3' THEN 'FAILED'
    WHEN 'CAPTURED' THEN 'COMPLETED'
    WHEN 'PAID' THEN 'COMPLETED'
    WHEN 'SUCCESS' THEN 'COMPLETED'
    WHEN 'CREATED' THEN 'PENDING'
    ELSE status
END;

ALTER TABLE payment_order MODIFY COLUMN status VARCHAR(64) NULL;
ALTER TABLE payment_order MODIFY COLUMN payment_method VARCHAR(64) NULL;

UPDATE payment_order
SET status = CASE CAST(status AS CHAR)
    WHEN '0' THEN 'PENDING'
    WHEN '1' THEN 'SUCCESS'
    WHEN '2' THEN 'FAILED'
    WHEN 'CAPTURED' THEN 'SUCCESS'
    WHEN 'PAID' THEN 'SUCCESS'
    WHEN 'COMPLETED' THEN 'SUCCESS'
    WHEN 'CREATED' THEN 'PENDING'
    ELSE status
END;

UPDATE payment_order
SET payment_method = CASE CAST(payment_method AS CHAR)
    WHEN '0' THEN 'RAZORPAY'
    WHEN '1' THEN 'STRIPE'
    WHEN 'CARD' THEN 'STRIPE'
    WHEN 'ONLINE' THEN 'RAZORPAY'
    ELSE payment_method
END;
